### ISSUE TITLE
Would be nice to have a "Save As" feature for missions

### ISSUE THREAD

**Issue by dbaldwin** [dbaldwin/DroneBlocks-Web#12]

**Comment by ibrahimcengiz** [comment]
also missions can be saved without a name. But after that you can not open it because there is no letter to click.

**Comment by dbaldwin** [comment]
@ibrahimcengiz that's a good find. We will look into fixing this.

**Comment by dbaldwin** [comment]
We've implemented the "Save As" feature. Please give it a try. You'll likely need to uninstall your existing DroneBlocks app and reinstall because we cache a lot of the web components. Alternatively, you can go here and give it a try: https://dev.droneblocks.io?n=123456
