### ISSUE TITLE
Feature request - Variable in loops

### ISSUE THREAD

**Issue by basinger** [dbaldwin/DroneBlocks-Web#13]
It would be great if the "repeat x times" for the loops block could be a variable.
Today the x has to be selected and is fixed and can't be calculated or varied.

**Comment by dbaldwin** [comment]
This is resolved in the latest DroneBlocks release. If you have the app installed you may need to uninstall it and reinstall since we use caching. If you're accessing via the web you can see the variable loop block here:

https://dev.droneblocks.io/?n=113

Thanks for the suggestion @basinger
