### ISSUE TITLE
users / password hashes stored in GitHub? 

### ISSUE THREAD

**Issue by MAVProxyUser** [dbaldwin/DroneBlocks-Web#23]
You should probably delete this. 
https://github.com/dbaldwin/DroneBlocks-Web/blob/master/users.csv

**Comment by dbaldwin** [comment]
@MAVProxyUser wow. Good catch and somehow we committed this on accident. It has been purged from the repo. Thanks so much for pointing this out.

**Comment by MAVProxyUser** [comment]
Sure. Out of courtesy you should probably force the end users to reset passwords. No telling who pulled that down and cracked the hashes
