### ISSUE TITLE
I would really like to have this app work on the iphone 6s

### ISSUE THREAD

**Issue by mikeq3** [dbaldwin/DroneBlocks-Web#3]
I use an iPhone 6s with my quadcopter. Can you modify this program to work on that device please? I have an iPad pro but it is too big to bring for flying.
Mike

**Comment by dbaldwin** [comment]
Mike thanks for the feedback. This is definitely on the bucket list and once we get saving/sharing pushed to the app store this will be in the dev queue.

**Comment by dbaldwin** [comment]
The current version of DroneBlocks now works on the iPhone 6S. Please test and let us know if you have any problems.

**Comment by mikeq3** [comment]
Looks great! thank you!
